---
# ============================================================
# ocp-tasks/generate_install_config.yml
# Generate OCP install-config.yaml on Bastion
# ============================================================

# --------------------------------------------------------
# 1 - Load bastion_ip and network from file
# --------------------------------------------------------
- name: "Copy bastion_ip.txt to bastion"
  ansible.builtin.copy:
    src: "/home/{{ local_user }}/ocp-vcenter-ansible/bastion_ip.txt"
    dest: "/tmp/bastion_ip.txt"
    mode: "0644"

- name: "Load bastion info from file"
  ansible.builtin.slurp:
    src: "/tmp/bastion_ip.txt"
  register: bastion_ip_file

- name: "Set bastion facts"
  ansible.builtin.set_fact:
    bastion_ip: "{{ bastion_ip_file.content | b64decode | regex_search('bastion_ip: (.+)', '\\1') | first | trim }}"
    bastion_network: "{{ bastion_ip_file.content | b64decode | regex_search('bastion_network: (.+)', '\\1') | first | trim }}"



# --------------------------------------------------------
# 2 - Load SSH public key from vault
# --------------------------------------------------------
- name: "Set SSH public key fact from vault"
  ansible.builtin.set_fact:
    ssh_pub_key: "{{ bastion_ssh_public_key }}"

- name: "Ask for cluster name"
  ansible.builtin.pause:
    prompt: "Enter OCP cluster name (e.g. ocp)"
  register: cluster_name_input
  until: cluster_name_input.user_input | trim != ""
  retries: 5
  delay: 0
  

- name: "Ask for base domain"
  ansible.builtin.pause:
    prompt: "Enter base domain (e.g. nbe.gts)"
  register: base_domain_input
  until: base_domain_input.user_input | trim != ""
  retries: 5
  delay: 0

- name: "Set user input facts"
  ansible.builtin.set_fact:
    ocp_cluster_name: "{{ cluster_name_input.user_input | trim }}"
    ocp_base_domain: "{{ base_domain_input.user_input | trim }}"
    ocp_pull_secret: "{{ pull_secret }}"


# --------------------------------------------------------
# 4 - Create OCP installation directory on Bastion
# --------------------------------------------------------
- name: "Create OCP installation directory"
  ansible.builtin.file:
    path: /opt/ocp-install
    state: directory
    owner: root
    group: root
    mode: "0755"

# --------------------------------------------------------
# 5 - Generate install-config.yaml
# --------------------------------------------------------
- name: "Generate install-config.yaml"
  ansible.builtin.copy:
    dest: /opt/ocp-install/install-config.yaml
    owner: root
    group: root
    mode: "0644"
    force: true
    content: |
      apiVersion: v1
      baseDomain: {{ ocp_base_domain }}
      compute:
      - architecture: amd64
        hyperthreading: Enabled
        name: worker
        replicas: 0
      controlPlane:
        architecture: amd64
        hyperthreading: Enabled
        name: master
        replicas: 3
      metadata:
        name: {{ ocp_cluster_name }}
      networking:
        clusterNetwork:
        - cidr: 10.128.0.0/14
          hostPrefix: 23
        machineNetwork:
        - cidr: {{ bastion_network }}
        networkType: OVNKubernetes
        serviceNetwork:
        - 172.30.0.0/16
      platform:
        none: {}
      pullSecret: '{{ ocp_pull_secret }}'
      sshKey: '{{ ssh_pub_key }}'

# ------------------------------------------------------------------------------
# 6 - Backup install-config.yaml to Ansible machine & Bastion OCP installation
# --------------------------------------------------------------------------------
- name: "Backup install-config.yaml to Ansible machine"
  ansible.builtin.fetch:
    src: /opt/ocp-install/install-config.yaml
    dest: "/home/{{ local_user }}/ocp-vcenter-ansible/ocp-tasks/install-config.yaml"
    flat: true

- name: "Backup install-config.yaml"
  ansible.builtin.copy:
    src: /opt/ocp-install/install-config.yaml
    dest: /opt/ocp-install/install-config.yaml.bk
    remote_src: true
    owner: root
    group: root
    mode: "0644"

# --------------------------------------------------------
# 7 - Summary
# --------------------------------------------------------
- name: "install-config.yaml Summary"
  ansible.builtin.debug:
    msg:
      - "=================================================="
      - "  install-config.yaml Generated"
      - "=================================================="
      - "  Cluster Name : {{ ocp_cluster_name }}"
      - "  Base Domain  : {{ ocp_base_domain }}"
      - "  Machine Net  : {{ bastion_network }}"
      - "  Location     : /root/ocp-install/install-config.yaml"
      - "  Backup       : ocp-tasks/install-config.yaml"
      - "=================================================="